# Generated by Django 5.0.2 on 2025-03-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0004_alter_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
