# Generated by Django 5.0.2 on 2025-05-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0005_alter_maestros_materias_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipoEvento', models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=50, verbose_name='Tipo de evento')),
                ('fecha_realizacion', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('lugar', models.CharField(max_length=150)),
                ('publico', models.CharField(max_length=255, verbose_name='Objetivo del evento')),
                ('programaEducativo', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('cupoMaximo', models.PositiveIntegerField()),
            ],
        ),
    ]
