# Generated by Django 5.0.2 on 2025-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0006_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='tipoEvento',
            new_name='tipoE',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='publico',
        ),
        migrations.AddField(
            model_name='eventos',
            name='opsc',
            field=models.CharField(default='', max_length=255, verbose_name='Publico Objetivo'),
        ),
    ]
