# Generated by Django 5.0.2 on 2025-05-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0007_rename_tipoevento_eventos_tipoe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='opsc',
            new_name='publicoObjetivo',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='tipoE',
            new_name='tipoEvento',
        ),
    ]
